#! /bin/bash

if [ -d $1 ]
then 
    echo "$1 is a dir"
fi

if [ -f $1 ]
then 
    echo "$1 is a ordinary file"
fi

if [ -x $1 ] 
then 
    echo "file $1 is executable"
fi

if [ -w $1 ]
then 
    echo "file $1 is writable"
fi
    
