#! /bin/bash

# 统计 参数$1 目录下的文件（本级）个数

if [ $# -lt 1 ]
then
    echo "must supply a dir"
    exit 1
fi

count=0

for aF in `ls $1`
do
  if [ ! -d $aF ]
  then
       let count=$count+1
  fi
done

echo "There is $count files in $1"
